config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :boxes
  resources :users do 
  	resources :subscriptions, only: [:new, :show, :edit, :update, :destroy]
  end

  # root 'welcome#index'
  root :to => 'welcome#index'

  resources :subscriptions


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
	has_many :subscriptions
	has_many :users, through: :subscriptions

end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :box, optional: true
	belongs_to :subscriber, :class_name => "User", optional: true
	accepts_nested_attributes_for :box

	validates :level, presence: true

	# def box_attributes=(box)
	# 	self.box = Box.find_or_create_by(name: box.name)
	# 	self.box.update(box)
	# end

	def level_with_descript
		"#{level}, #{description}"
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :subscriptions, :foreign_key => 'subscriber_id'
  has_many :boxes, through: :subscription

  	def self.from_omniauth(auth)
  		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.name = auth.info.name
      	user.email = auth.info.email
      	user.password = Devise.friendly_token[0,20]
    	end      
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	def after_sign_in_path_for(resource)
  		request.env['omniauth.origin'] || root_path
	end
	
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController

	def index
		@boxes = Box.all
		respond_to do |format|
			format.html { render :index }
			format.json { render json: @boxes }
		end
	end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	before_action :set_subs
	before_action :set_user

	def index
		@subs = Subscription.all
		respond_to do |format|
			format.html { render :index }
			format.json { render json: @subs } 
		end
	end
	
	def new
		@subs = Subscription.new
		@subs.build_box
	end

	def create
		@subscription =  Subscription.new(subs_params)
		if @subscription.valid?
	 		@subscription.save
	 		current_user.subscribed = true
			render json: @subscription 
 		else
 			render :new 
 		end
	end

	def show
		respond_to do |format|
			format.html { render :index }
			format.json { render json: @subs }
		end 
	end

	def edit
	end

	def update
		if @subs.update(subs_params)
			redirect_to user_subscription_path(current_user, @subs), notice: 'Your Subscription is Updated.'
		else
			render :edit
		end
	end

	def destroy
		@subs.delete
		redirect_to user_path(current_user), notice: 'Your Subscription is Canceled.'
	end


	private


	def subs_params
		params.require(:subscription).permit(:subscriber_id, :level, :description, box_attributes: [:title])
	end

	def set_user
		@user = User.find_by(id: params[:id])
	end	

	def set_subs
		@subs = Subscription.find_by(id: params[:id])
	end
	
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
  	sign_in_and_redirect @user   
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user
	before_action :set_subs

	def show
    	respond_to do |f|
	      f.html { render :show }
	      f.json { render json: @user }
    	end
	end

	def edit 
	end

	def update
		if user_signed_in? && current_user == @user
			current_user.update(user_params)
		end
		redirect_to user_path(current_user) 
	end

	def destroy
	end

	private


	def set_user
		@user = User.find_by(id: params[:id])
	end

	def user_params
		params.require(:user).permit(:name)
	end

	def set_subs
		@subs = Subscription.find_by(id: params[:id])
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@user = current_user
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boxes/index.html.erb
<div class="boxes-container">

	<table class="table">
	  <tr class="tr">
	  	<% @boxes.first(1).each do |box| %>
	   		<th class="th"></th>
		<% end %>
	  </tr>
	  <tr>

	</table>
	
</div> 

app/views/layouts/_navigation.html.erb
<% if !user_signed_in? %>
    <div class="container">
      <div class="row" id="nav-bar">
        <div class="col-md-4" id="logo-column1"><%= link_to "BitBox", root_path, :class => 'logo' %></div>
        <div class="col-md-4" id="logo-column2"><%= link_to "Shop", boxes_path, :class => 'logo-2'%></div>
        <div class="col-md-4" id="logo-column3">
          <%= link_to new_user_session_path, :class => 'logo-3' do %>
            <i class="fa fa-user"></i> 
          <%end%>
          <%= link_to boxes_path, :class => 'logo-3' do %>
            <i class="fa fa-shopping-cart"></i> 
          <% end %>
        </div>
      </div>
    </div> 
<!-- 
    <div class="row" id="nav-bar">
      <div class="col-xs-12 col-sm-6 col-md-8">
        <%= link_to "BitBox", root_path, :class => 'logo' %>
      </div>
      <div class="col-xs-6 col-md-4">
        <%= link_to new_user_session_path, :class => 'logo-2' do %>
          <i class="fa fa-user"></i> 
        <% end %> 
        <%= link_to boxes_path, :class => 'logo-2' do %>
          <i class="fa fa-shopping-cart"></i> 
        <% end %> 
      </div>
    </div>  -->

	 <% else %>
   <div class="container">
      <div class="row" id="nav-bar">
        <div class="col-md-4" id="logo-column1"><%= link_to "BitBox", root_path, :class => 'logo' %></div>
        <div class="col-md-4" id="logo-column2"><%= link_to "Shop", boxes_path, :class => 'logo-2'%> |  <%= link_to current_user.name, user_path(current_user), :class => "user"%> | <%= link_to "Get Started", subscriptions_path, :class => "logo-5" %>  </div>
        <div class="col-md-4" id="logo-column3">
          <%= link_to new_user_session_path, :class => 'logo-3' do %>
            <i class="fa fa-user"></i> 
          <%end%>
          <%= link_to destroy_user_session_path, :class => 'logo-4', method: :delete do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </div>
      </div>
    </div> 
<!-- 	   <center><h1><%= link_to "BitBox", root_path %> | <%= link_to "Shop", boxes_path %> | <%= link_to current_user.name, user_path(current_user), :class => "user"%> | <%= link_to "Get Started", subscriptions_path %> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </h1></center>
	    <br>
	    <br> -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>🤖Bitbox</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body class="<%= controller_name %> <%= action_name %>">	
  <%= render 'layouts/navigation' %>
    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
    <%= yield %>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<% if @subs.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@subs.errors.count, "error") %>
      prohibited this subscription from being saved:
    </h2>
 
    <ul>
    <% @subs.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @subs, :html => {:class => 'subscription'} do |f| %>
	<%= f.hidden_field :subscriber_id, :value => current_user.id %>
	<%= f.label :level, "Monthly Plan" %><br><br>
	<%= f.collection_select(:level, Subscription.first(3), :level_with_descript, :level) %><br>
  <br> <%= f.submit "Subscribe", :class => 'btn btn-secondary btn-sm active' %>
<% end %>

app/views/subscriptions/_info.html.erb
<strong>STARTER BOX</strong><br>
What You'll Get<br>
---<br>
8+ INVENTIONS<br>
(+ Thousands More Online & On the App!)<br><br>

76-PAGE INVENTION GUIDEBOOK<br>
Step-by-step instructions that guide you from simple circuit building to mind-blowing inventions.<br>
---<br>

For ages 8+<br><br><br>

<strong>ADVANCED BOX</strong><br>
What You'll Get<br>
---<br>
3+ INVENTIONS<br>
(+ Thousands More Online & On the App!)<br><br>

24-PAGE INVENTION GUIDEBOOK<br>
Step-by-step instructions that guide you from simple circuit building to mind-blowing inventions.<br>
---<br>
For ages 12+<br><br><br>

<strong>SUPER PRO BOX</strong><br>
What You'll Get<br>
---<br>
3+ INVENTIONS<br>
(+ Thousands More Online & On the App!)<br><br>

24-PAGE INVENTION GUIDEBOOK<br>
Step-by-step instructions that guide you from simple circuit building to mind-blowing inventions.<br>

---<br>
For ages 16+<br>

*All plans will automatically renew but may be canceled at anytime. Applicable taxes not included.

app/views/subscriptions/edit.html.erb
<%= render 'form' %><br>

<%= button_to "Back", user_path(current_user), method: :get%>

app/views/subscriptions/index.html.erb
<div class="subs-container">
  <h2><center> MONTHLY PLAN </center></h2></div><br><br>


  <table border="1" cellpadding="50" class="subs" >
    <tr>
      <td class="table" id="1"></td>
      <td class="table" id="2"></td>
      <td class="table" id="3"></td>
    </tr>
  </table>



  <div class="container" id="subs-info">
  <div class="row" >
  <div class="col-sm-12" >  <div class="box-info"></div> </div>
  </div>


</div>

app/views/subscriptions/new.html.erb
<div class="col-lg-6 col-sm-6">
	<div class="monthly-plan">
	    <div class="card hovercard">
	        <div class="card-background">
	            <img class="card-bkimg" alt="" src="https://pic.funnygifsbox.com/uploads/2014/08/4f21a08e1662846cf733146d19f6b994.gif">
	        </div>
	        <div class="useravatar">
	            <img alt="" src="https://pic.funnygifsbox.com/uploads/2014/08/4f21a08e1662846cf733146d19f6b994.gif">
	        </div>
	        <div class="card-info"> 
	        	<h2> Subscribe to BitBox </h2>
	        </div>
	    </div>

	    <div class="card hovercard" id="profile-buttons">
	   		<div class="row" >
	   		<%= render 'form' %><br>
			<%= button_to "Back", user_path(current_user), method: :get, :class => 'btn btn-secondary btn-sm active' %>
	    	</div>
		</div>
	</div>
</div>
    

app/views/subscriptions/show.html.erb
<h2> Active Subscription </h2>
<h3> <%= current_user.name %></h3>

<%= render 'users/current' %><br>
<%= link_to 'Edit', edit_user_subscription_path(current_user, @subs)%>
<%= link_to 'Cancel', user_subscription_path(current_user, @subs), method: :delete %>

app/views/users/_current.html.erb
<% if !current_user.subscriptions.empty? %>
	<% current_user.subscriptions.each do |sub| %>
		<% if !sub.subscriber_id = nil %>
			<h3> BitBox: </h3>
			<%= sub.level %><br>
			<% @date = sub.updated_at %>
			<br>Started on: <%= @date.strftime("%m/%d/%Y") %><br><br>
			<%= link_to "Cancel Subscription", subscription_path(sub), method: :delete %>
		<% end %>
	<% end %><br>
<% else %>
	You Are Not Subscribed.
<% end %>

app/views/users/edit.html.erb
<div class="user-container">

	<div class="col-lg-6 col-sm-6">
	    <div class="card hovercard">
	        <div class="card-background">
	            <img class="card-bkimg" alt="" src="https://pic.chinesefontdesign.com/uploads/2014/08/2b81522a7845748a5c36e5ae3bd28d4b.gif">
	        </div>
	        <div class="useravatar">
	            <img alt="" src="https://pic.chinesefontdesign.com/uploads/2014/08/2b81522a7845748a5c36e5ae3bd28d4b.gif">
	        </div>
	        <div class="card-info"> 
	        	<h2>Edit Your Profile </h2>
	        </div>
	    </div>

	    <div class="card hovercard" id="profile-buttons">
	   		<div class="row" >
	   		<%= form_for current_user do |f| %>
				<%= f.label :name, :class => "profile-name" %>:
				<%= f.text_field :name %><br><br>
				<%= f.submit 'Update', :class => 'btn btn-secondary btn-sm active' %>
			<% end %> <br>
			<%= button_to  'Back', user_path(current_user), method: :get, :class => 'btn btn-secondary btn-sm active' %>
	    	</div>
		</div>

    </div>
    
</div>

app/views/users/show.html.erb
<div class="user-container">

	<div class="col-lg-6 col-sm-6">
	    <div class="card hovercard">
	        <div class="card-background">
	            <img class="card-bkimg" alt="" src="https://pic.chinesefontdesign.com/uploads/2014/08/2b81522a7845748a5c36e5ae3bd28d4b.gif">
	        </div>
	        <div class="useravatar">
	            <img alt="" src="https://pic.chinesefontdesign.com/uploads/2014/08/2b81522a7845748a5c36e5ae3bd28d4b.gif">
	        </div>
	        <div class="card-info"> 
	        </div>
	    </div>

	    <div class="card hovercard" id="profile-buttons">
	   		<div class="row" >
		       <div class="col-md-4" id="profile-buttons-2">  
		          <%= button_to "EDIT YOUR PROFILE", edit_user_path(current_user), method: :get, :class => 'btn btn-secondary btn-lg active' %><br><br>
		       </div>
		       <div class="col-md-4" > 
				<%= button_to "SUBSCRIBE TO PLAN", new_subscription_path, method: :get, :class => ' btn btn-secondary btn-lg active', :id => "profile-buttons-3" %>
		       </div>
	    	</div>
		</div>

	      <div class="well">
		      <div class="tab-content">
		        <div class="tab-pane fade in active" id="tab1">
			       <br><h2>Current Plan</h2>
					<%= render "current" %>
				</div>
		      </div>
	    	</div>
    </div>
    
</div>

app/views/welcome/index.html.erb
<div id="myCarousel" class="carousel slide span12">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img class="d-block img-fluid" src=https://s3.amazonaws.com/lb-spree/spree/products/3046/large/ryr-kit.jpg?1477951666 alt="First slide">
            </div>
            <div class="item">
              <img class="d-block img-fluid" src="https://s3.amazonaws.com/lb-spree/spree/products/3033/large/ack-kit.jpg?1471356817" alt="Second slide">
            </div>
            <div class="item">
              <img class="d-block img-fluid" src="https://s3.amazonaws.com/lb-spree/spree/products/3006/large/SHK-Reskin-wBits_HR.jpg?1469125020" alt="Third slide">
            </div>
        </div>
    </div>
</div>

<div class="card w-50">
  <div class="card-block"><br>
    <h3 class="card-title" > What is </h3>
    <h3 class="card-title" id="second-title"> BitBox? </h3><br>
    <p class="card-text">BitBox is a diy product that encourages everyone regardless of age to create inventions.</p>
  </div><br>
</div>